### ISSUE TITLE
How to dispose an observable returned by workFactory?

### ISSUE THREAD

**Issue by nikita-leonov** [RxSwiftCommunity/Action#100]
I have a hard time to dispose an observable produced by the action's workFactory. It seems that `Observable` returned by execute is not the same as `Observable` returned by work factory. Disposing it does not dispose an internal observer and does not reset enabled. What is the recommended way to programmatically stop execution of an observable that was created by workFactory and currently being executed by Action?

Here is my ugly test code:
```
import RxSwift
import Action
import UIKit

class ViewController: UIViewController {
    let action = Action<Void, Int> { _ in Observable<Int>.interval(1, scheduler: MainScheduler.instance) }
    var actionDisposable = Disposable?.none
    
    @IBAction func initiateAction() {
        actionDisposable = action.execute().bind(onNext: { print("\($0)") })
    }
    
    @IBAction func stopAction() {
        actionDisposable?.dispose()
    }
}
```

It does stop printing, but it does not re-enable action, as well as does not stop timer.

**Comment by ashfurrow** [comment]
Hey there, sorry for the issue! I think what you'll want to do is use `takeUntil` to send a `completed` event to the observable returned by the factory. That should take care of re-enabling the action. Let me know if I can clarify anything, good luck!

**Comment by nikita-leonov** [comment]
Yeah, great idea to have it defined in a factory. It definitely solves problem! 

Here is a sample code that end-up with:
```
class ViewController: UIViewController {
    let bag = DisposeBag()
    var action: Action<Void, Int>!
    
    @IBOutlet weak var startButton: UIButton!
    @IBOutlet weak var stopButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        action = Action<Void, Int> { [weak stopButton] Void -> Observable<Int> in
            guard let stopButton = stopButton else {
                return .empty()
            }
            return Observable<Int>.interval(1, scheduler: MainScheduler.instance).takeUntil(stopButton.rx.tap)
        }
        action.elements.bind(onNext: { print("\($0)")}).disposed(by: bag)
        startButton.rx.bind(to: action, input: ())        
    }
}
```

Seeing an action returning an observable that is not subscribed anywhere and the whole thing still executing after ReactiveSwift implementation feels a little bit odd. Is there a reason to have Observable from `execute` and `executingObservable` serve the same purpose. In ReactiveSwift world Action was a producer of producers, so when you do execute it returns procure that should be started and if it is not nothing is happening, if it is disposed then an internal producer disposed too. Here dispose of execute's Observable stops the observation of elements, but not an execution itself. I guess it is question of design, but in general having this 'side-effect-like' take until somewhere in a factory looks suspicious.

**Comment by ashfurrow** [comment]
Yeah, I'm not sure what the best / most idiomatic solution would look like. In this specific case, having a button execution an action, you could also try using the `rx.action` property on `UIButton`. Let me know if I can clarify anything!

**Comment by mrRedSun** [comment]
Take until looks like a great solution, I believe this issue should be closed
