### ISSUE TITLE
Bind an action to a button with observable input

### ISSUE THREAD

**Issue by djsison** [RxSwiftCommunity/Action#111]
I'm new to Rx, and I've just started looking at Actions too. This question may sound silly, so please bear with me.

I have a screen with a text field and a button to submit the form.
What I would like to do is bind the button to an Action while passing the text field text observable as input to the action. How can I do this?

What I would like to do is something like this:
`button.rx.bind(to: viewModel.action, input: textField.rx.text)`
Or, if I have two text fields:
`button.rx.bind(to: viewModel.action, input: Observable.combineLatest(textField1.rx.text, textField2.rx.text))`
Is this possible? Does this even make sense to you guys?

I know that I can pass input using another way (see below), but I would like to avoid capturing self if possible. And also, the code above seems more reactive to me.
`
button.rx.bind(to: viewModel.action) { _ in
    return self.textField.text
}
`

Thoughts?

**Comment by djsison** [comment]
Oops, just found out the answer when I read through the Action source code.
I can do it like this:
`button.rx.tap.withLatestFrom(textField.rx.text).bind(to: viewModel.action.inputs).disposed(by: disposeBag)`

**Comment by Blackening999** [comment]
I'm trying to do the same and see
```Cannot invoke 'bind' with an argument list of type '(to: InputSubject<(String, String)>)'```
Can someone help me out?

**Comment by Dfmarulanda** [comment]
I'm doing this, but the action is executed only once; even if more inputs are emitted when i tap the button.
