### ISSUE TITLE
Switch to Circle CI

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/Action#117]
Travis builds are taking hours just to queue, we need to switch to Circle to get faster feedback. I'll get to this eventually, if someone else wants to take it on, by all means 😄

**Comment by bobgodwinx** [comment]
I was just talking to them in Berlin it seems they have serious issues. I've learnt from yesterday deployment.

**Comment by ashfurrow** [comment]
Maybe they should update their status page 😛 

<img width="939" alt="screen shot 2017-10-19 at 9 52 12 am" src="https://user-images.githubusercontent.com/498212/31774247-33872bb4-b4b3-11e7-9c22-61371d634345.png">

I hope they get things resolved, but this issue isn't about today's delays; Travis has had long wait times for macOS builds for a long time. I wish Travis the best ❤️

**Comment by bobgodwinx** [comment]
Me too let's wait another hour if not.  You just test `Action` locally and pushed to CocoaPods trunk. Main while I will draft the release in gitHub.
