### ISSUE TITLE
Carthage ~> 2.3.0 checks out "2.0.0-beta.1"

### ISSUE THREAD

**Issue by belakva** [RxSwiftCommunity/Action#129]
So Carthage `~> 2.3.0` checks out `2.0.0-beta.1`. 
But I need RxSwift 4.0 ver.
Checking out `master` (d2cc0e9b9de6451b58dd77a690a32c2e26e7cd04) fails to build with error:
`The following build commands failed:
	CompileC /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B46/Action/d2cc0e9b9de6451b58dd77a690a32c2e26e7cd04/Build/Intermediates.noindex/ArchiveIntermediates/Action/IntermediateBuildFilesPath/Rx.build/Release-iphoneos/RxCocoa-iOS.build/Objects-normal/armv7/_RXObjCRuntime.o RxCocoa/Common/_RXObjCRuntime.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

NB: I am using Carthage to build static lib of **Action**.

What can be done?

**Comment by bobgodwinx** [comment]
Please try this it should clean it up:  `carthage update --use-submodules --no-build`
