### ISSUE TITLE
Carthage error upgrading from 3.4.1 to 3.5.0

### ISSUE THREAD

**Issue by a141144** [RxSwiftCommunity/Action#130]
Running `carthage update Action --no-build --no-use-binaries` ends up with this error:

```
Parse error: expected submodule commit SHA in output of task (ls-tree -z 3.5.0 Carthage/Checkouts/RxSwift) but encountered: 
```

I'm not sure if this is because you deleted the Submodules or because of a bug in Carthage.  I'm using Carthage 0.26.2.

**Comment by a141144** [comment]
I think d077b251d71d2ce823712c1602adf78300e773c6 by @XavierDK fixes this.

**Comment by a141144** [comment]
@ashfurrow Perhaps a `3.5.1` tag that includes this commit is wise.

**Comment by ashfurrow** [comment]
Good thinking @a141144 – apologies for letting this slip through the cracks, and thanks for the issue. I've created a tag and GitHub release of 3.5.1, please let me know how it goes.
