### ISSUE TITLE
Underlying Errors in Action Not Propagated to Subscription Block

### ISSUE THREAD

**Issue by rrozenv** [RxSwiftCommunity/Action#131]
I was hoping if someone could help me out and explain why I don't receive error events when an underlying error occurs inside the action block. Below I have provided the necessary code from my view controller and view model (note: I named my viewModel "engine"). 

The issue is that inside the Action named 'registerAction', the observable related to: RealmLoginManager.register(email: userInput.email, password: userInput.password) produces an error event. However the subscription block to the error event never fires inside my view controller. 

Thank you!

```
View Controller  -------------

        registerButton.rx.tap
            .withLatestFrom(engine.userInput)
            .bind(to: engine.registerAction.inputs)
            .disposed(by: disposeBag)
        
        engine.registerAction
            .elements
            .subscribe(onNext: { (user) in
                print("Successfully created \(user.userName)!")
            })
            .disposed(by: disposeBag)
        
        engine.registerAction
            .errors
            .subscribe(onError: { (error) in
                print(error.localizedDescription)
            })
            .disposed(by: disposeBag)

```

```
View Model  -------------
    lazy var registerAction: Action<UserInput, User> = { me in
        return Action { (userInput) in
            return RealmLoginManager
                .register(email: userInput.email, password: userInput.password)
                .flatMap { _ -> Observable<User> in
                    return me.userDataController.create(name: userInput.userName, email: userInput.email)
                }
        }
    }(self)

```

**Comment by mosamer** [comment]
`Action.errors` is an `Observable<ActionError>`, which means errors are emitted as `next` events not as errors. Try to change your code to look like the following;

```diff
engine.registerAction
   .errors
-   .subscribe(onError: { (error) in
+   .subscribe(onNext: { (error) in
      print(error.localizedDescription)
   })
   .disposed(by: disposeBag)
```

**Comment by rrozenv** [comment]
Ahh I see, now it's working as expected. Thank you for the quick reply, I appreciate it!
