### ISSUE TITLE
On binding RxAction to `UITextField`'s `editingChanged` control event, causes `UITextField` to loose focus

### ISSUE THREAD

**Issue by sandeeplearner** [RxSwiftCommunity/Action#143]
I have a simple validator action, and the criteria for the validation is as simple as text character count should be greater than 0. I have multiple textFields and would like to check if all textFields have appropriate data

```
validatorAction = Action<Void,Bool> {
            return Single<Bool>.create(subscribe: { (single) -> Disposable in
                if self.firstName.text?.count ?? 0 > 0 && self.lastName.text?.count ?? 0 > 0 && self.age.text?.count ?? 0 > 0 {
                    single(.success(true))
                }
                else {
                    single(.success(false))
                }
                return Disposables.create()
            })
       }
```

Now I bind this validator action to all the textFields as 

```
self.firstName.rx.bind(to: validatorAction, controlEvent: self.firstName.rx.controlEvent(UIControlEvents.editingChanged)){ (textField) -> Void in
            return Void()
        }
        
        self.lastName.rx.bind(to: validatorAction, controlEvent: self.lastName.rx.controlEvent(UIControlEvents.editingChanged)){ (textField) -> Void in
            return Void()
        }
        
        self.age.rx.bind(to: validatorAction, controlEvent: self.age.rx.controlEvent(UIControlEvents.editingChanged)) { (textField) -> Void in
            return Void()
        }

```

Finally I bind the `validatorAction` to a buttons enabled state

```
 validatorAction.elements
            .asObservable()
            .startWith(false)
            .asDriver(onErrorJustReturn: false)
            .drive(self.submitButton.rx.isEnabled)
            .disposed(by: self.disposeBag)
```

**Issue:**

Every time a character is changed in any of the textField validator action executes and causes the textField to loose its focus. Is that intentional ? Because the user experience seems to suffer a lot with in its current state.

**Comment by ashfurrow** [comment]
Hi there! It sounds like you're slightly misusing the closure that's passed into the `Action` initializer. You'll want to try using the full initializer `Action(enabledIf:, workFactory:)` to separate out one closure to enable/disable the action, and another closure to return an observable of whatever work you want done. You can then bind the action to the button and it will handle enabling/disabling it for you. Check out [the readme](https://github.com/RxSwiftCommunity/Action#usage) for more information and let us know how it goes.

**Comment by sandeeplearner** [comment]
@ashfurrow : Thanks for the response. But I am still facing issue with integrating RxAction to validate textFields and enable button only if text in TextFields are valid. Can you please add an example to demo the same. I tried creating Action with full initializer, but seems like I have been using actions wrong inherently. Will be really helpful if you can add a example. No need for complete code, just the mock would do :)

**Comment by sandeeplearner** [comment]
@ashfurrow : Thanks a lot, I got it now. Really helpful. I had misunderstood RxAction conceptually, looking at your code helped me :) Thanks

**Comment by ashfurrow** [comment]
@sandeeplearner I'm glad to hear that! You requested a more detailed example from the Readme, and I think that's a good idea. Would you be interested in writing one and sending a pull request? It would be awesome if other people could benefit from what you've learned. No pressure though! I know everyone is busy 😄

**Comment by sandeeplearner** [comment]
@ashfurrow : Am really sorry for the delayed reply, I would love to add a PR but before seeking out help here I had raised a same question in SO and somebody answered exactly the same thing I ended up coding after getting your help here. Though the answer in SO came little late but its exactly same as mine. So am leaving the link here, take a look if u are ok with it I can request the OP to raise a PR with an example

https://stackoverflow.com/questions/50232330/how-to-create-rxaction-to-enable-disable-button-if-text-in-uitextfield-is-va

**Comment by ashfurrow** [comment]
That's a good answer. I think your contribution to the readme would still be valuable – it's important to document things as we learn them – but no pressure of course.
