### ISSUE TITLE
Podspec version number

### ISSUE THREAD

**Issue by raphrel** [RxSwiftCommunity/Action#145]
Trying to use pod Action 3.5.2
3.5.2 && 3.5.1 tag commits mention 3.5.0 version in the podspec file.

So cocoapods could not find compatible > 3.5.0
Is there any reason I missed ?

**Comment by ashfurrow** [comment]
Hey, the podspec versions in the tagged releases don't matter, it's only what's on CocoaPods trunk, which you can find out by `pod trunk info Action`. The last two patch [releases](https://github.com/RxSwiftCommunity/Action/releases), 3.5.1 and 3.5.2, fix Carthage problems only, and so weren't released to CocoaPods. Use a `>= 3.50` or, better yet, a `~> 3.5` in your Podfile. Let me know what I can clarify.

**Comment by raphrel** [comment]
Fine, I did understand, I didn't expect Cathage and Pod differ from version.
Thanks

**Comment by bobgodwinx** [comment]
@ashfurrow I think though we should unify the this now under the same semantic versioning what do you think?

**Comment by ashfurrow** [comment]
It's probably fine – I was just being lazy 😛 It's been operating this way since January, there are no code changes, but if someone would like to publish new versions to CocoaPods that's fine with me too 👍

**Comment by bobgodwinx** [comment]
@ashfurrow I will do that tomorrow. I just need to text everything b4 pushing.

**Comment by ashfurrow** [comment]
Sounds good 👍 I've made sure that the shared RxSwiftCommunity CocoaPods account is an owner of the pod, let me know if I can help.

**Comment by bobgodwinx** [comment]
@ashfurrow I think you didn't add my email please cross check because I am getting this
`[!] You (bobgodwinx@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are ash@ashfurrow.com, fpillet@gmail.com, and community@rxswift.org.`
but all good.. you just need to add it so I can `pod trunk push Action.podspec`

**Comment by ashfurrow** [comment]
Cool, sorry about that @bobgodwinx I thought you had the community@rxswift.org account. Should be good to go now 👍
