### ISSUE TITLE
build failed with carthage

### ISSUE THREAD

**Issue by cohena100** [RxSwiftCommunity/Action#147]
### Cartfile:
github "ReactiveX/RxSwift" "4.2.0"
github "RxSwiftCommunity/Action" "3.6.0"

### Xcode version 9.4.1.

Build is failing with this error:
`.../Carthage/Checkouts/Action/Carthage/Checkouts/RxSwift/RxSwift/Concurrency/Lock.swift:49:38: error: attribute can only be applied to types, not declarations
      func calculateLockedOrFail<T>(@noescape action: () throws -> T) throws -> T {`

Build is failing when using either one of these:
`carthage update --platform iOS `
`carthage update --platform iOS --no-use-binaries`

**Comment by bobgodwinx** [comment]
@cohena100 please try cleaning or removing the `Carthage` directory before building. it works like a charm 👉🏾
![screen shot 2018-07-05 at 17 27 47](https://user-images.githubusercontent.com/675504/42332714-02ea2c76-8079-11e8-8935-0e5d67891120.png)
let me know how it goes. Thanks

**Comment by bobgodwinx** [comment]
@cohena100 sorry for the late reply but I tested it and it works for me. Maybe try deleting your `Carthage` folder first and run the command again. 
👉🏾 
![screen shot 2018-07-05 at 17 46 51](https://user-images.githubusercontent.com/675504/42333662-a61c3c66-807b-11e8-90dd-029a62628b89.png)

**Comment by cohena100** [comment]
That was indeed the case. Thanks man!
