### ISSUE TITLE
Improvement of UIRefreshControl support 

### ISSUE THREAD

**Issue by vldalx** [RxSwiftCommunity/Action#148]
[UIRefreshControl support has been recently added](https://github.com/RxSwiftCommunity/Action/pull/144) by @stefanomondino.
Everything works perfectly until an action is run programmatically.

Let say I have
``` Swift
let refreshControl = UIRefreshControl()
```
and
``` Swift
let refreshCommand = Action<Type1, Type2> { arg in
   // data is being fetched from a remote source
}
```
are binded 
``` Swift
refreshControl.rx.bind(to: refreshCommand, inputTransform: { _ in Type1() })
```

If the `refreshCommand` is run programmatically `refreshCommand.execute(Type1())` then the `refreshControl` will appear and UI will be broken.

I propose to change the code
https://github.com/RxSwiftCommunity/Action/blob/ab399062ffda1b94349ac408e543d05ab960ae71/Sources/Action/UIKitExtensions/UIRefreshControl%2BAction.swift#L41-L44
to 
``` Swift
action
.executing
.filter(!)
.bind(to: self.isRefreshing)
.disposed(by: self.base.actionDisposeBag)
```

I have tested this change in my application. A `Pull-to-refresh` gesture runs an action but a programmatically run action doest'n make `UIRefreshControl` visible.

**Comment by stefanomondino** [comment]
hi @vldalx ,
I don't know if I'm understanding this properly.
What do you mean by "UI will be broken"? 
In my opinion, if you bind the state of a component to an action, that component should follow the action regardless of any reason that triggered that action itself.
An action can be shared across components, so if you are triggering that action programmatically and don't want to see the activity indicator loading, simply don't bind it with the standard method.
For example, if you bind an Action to a UIButton, and then trigger it programmatically, that button will become disabled until the action completes.

**Comment by vldalx** [comment]
Hi @stefanomondino 
Thank you for the quick answer.
I've just figured out the UI problem seems like is an AsyncDisplayKit bug (I use it in my app).
In the `viewDidLoad` method I bind an action to a `UIRefreshControl` and run the action programmatically (it runs `UIRefreshControl` before the layout is calculated). As a result, however, an excess offset appears at the top of `ASTableNode`.
There is no such bug with the regular `UITableVIew`.
