### ISSUE TITLE
Move to Org

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/Action#15]
See: https://github.com/RxSwiftCommunity/contributors/issues/4

Copy steps from: https://github.com/RxSwiftCommunity/NSObject-Rx/issues/3 : 

- Update podspecs with new remote URL
- Update CI badge
- Update CI settings
- Tidy up readme and other things that reference "Ash Furrow", since it'll be a community project.
- Fork the repo back to my personal account (I _really_ don't feel like sending a PR to fix CocoaPods trunk, forking is so much easier)

**Comment by orta** [comment]
It might need a rename too

**Comment by ashfurrow** [comment]
Oh?

**Comment by orta** [comment]
Action doesn't really imply that it's heavily based on unlike: RxSwift. NSObject-Rx, RxViewModel, RxAlamofire

**Comment by ashfurrow** [comment]
Yeah, I suppose. I kind of like it as "Action", though :smile_cat:

**Comment by orta** [comment]
I'm not necessarily sure that it lives up to it's name though, for example should Esteban have called RxViewModel: ViewModel?

**Comment by fpillet** [comment]
I think `RxAction` would be an appropriate name - `Action` is fine but too generic and not easily discoverable.

**Comment by nanoxd** [comment]
Agreed with @orta and @fpillet on rename.

**Comment by ashfurrow** [comment]
I dunno, I like the boldness of it. "Action" is good branding imo –  `Action` makes no excuses for being generic because it is _so awesome_. If it's under the org, it'll be discoverable, and it's already near the top of CocoaPods search:

![screen shot 2015-12-07 at 1 43 24 pm](https://cloud.githubusercontent.com/assets/498212/11636134/850ee308-9ce8-11e5-92a4-16bc4b000f29.png)

**Comment by ashfurrow** [comment]
Should be good to go, going to monitor the next CI build.
