### ISSUE TITLE
Question: Where are the codes for "the private managed subscriptions for control"?

### ISSUE THREAD

**Issue by DhbStudy** [RxSwiftCommunity/Action#164]
For commom behavior, we need to subscribe the return results of elements(), like this:
```
loginAction.elements
  .filter { $0 } // only keep "true" values
  .take(1)       // just interested in first successful login
  .subscribe(onNext: {
    // login complete, push the next view controller
  })
  .disposed(by: disposeBag)
```
But for controls like Button, I can just bind and the events are emitted, like:
```
addOutlet.rx.tap
            .bind(to: requestNextPageAction.inputs)
            .disposed(by: disposeBag)
```
How that happened? I can't find where here are the codes? Can help me?

**Comment by ashfurrow** [comment]
Do you mean this code? https://github.com/RxSwiftCommunity/Action/blob/master/Sources/Action/CommonUI/Button%2BAction.swift
