### ISSUE TITLE
help!! why those code not working

### ISSUE THREAD

**Issue by plumhly** [RxSwiftCommunity/Action#165]
when i tap button, but not print "plum", i don't know where is wrong. please help me. 

```code
    let action = Action<String, String> { input in
        print("plum")
        return .just(input)
    }
    
    var button = UIButton(type: .custom)
    button.frame = CGRect(x: 0, y: 100, width: 200, height: 200)
    button.backgroundColor = .red
    button.rx.bind(to: action) { _ -> String in
        return "hello"
    }
```

**Comment by mudox** [comment]
You should strongly retain the action object somewhere (e.g. in your view controller instance).
The `bind` method does not retain the passed in `Action` instance on receiver, while the `action` property does.

**Comment by plumhly** [comment]
thanks, you solved my problem
