### ISSUE TITLE
Conflict With Other SDK

### ISSUE THREAD

**Issue by SuYungCheng** [RxSwiftCommunity/Action#178]
I use the other sdk name: Zendesk
they all have Action method.
When they use in the same class,
it shows "Action is ambiguous for type lookup in this context"
how to fix it?
![image](https://user-images.githubusercontent.com/17446246/53281396-b08f1300-3762-11e9-9ae9-d6db86cd0dba.png)

Thanks

**Comment by stefanomondino** [comment]
Use Action.Action to disambiguate

**Comment by stefanomondino** [comment]
You can also typealias one of those actions somewhere in your cose and use that alias instead (typalias ZAction = Zendesk.Action or typealias AAction =Action.Action)

**Comment by SuYungCheng** [comment]
thanks 
But I had tried Action.Action and zendesk.action
![image](https://user-images.githubusercontent.com/17446246/53285313-07640f00-379a-11e9-8c95-0406ab7b5137.png)

![image](https://user-images.githubusercontent.com/17446246/53285329-337f9000-379a-11e9-909c-037fafea3e74.png)

It says no Action member in Action and Zendesk

**Comment by SuYungCheng** [comment]
and also no Action.Action in the func return
![image](https://user-images.githubusercontent.com/17446246/53285448-79892380-379b-11e9-9676-53874d81e5f1.png)

**Comment by stefanomondino** [comment]
I'm not completely sure that autocomplete will help you out on this. Did you try to manually write Action.Action and try to compile anyway?

**Comment by stefanomondino** [comment]
this is also tricky since `Action` is, at the same time, the name of our library and the name of the actual class. in this case, I'd suggest to create a separate file, with only
```
import Action
typealias AAction = Action
```
 ("AAction" is really ugly, please try to find something more suitable :D I'd use something like `Selection` or `Command`) 

In the rest of your code, you should be able to use the alias instead. 

Another thing you could try to do is to break up your code in more little pieces, and see if you can import Zendesk only where it's really needed (and hopefully where Action is NOT needed). Is zendesk imported through Bridging Header?

**Comment by SuYungCheng** [comment]
I had thought that it's my project's problem.
But after I created a new project and installed pod file Action.
I tried Action.Action.
it failed the same with my original project.
![image](https://user-images.githubusercontent.com/17446246/53302584-745ece00-389a-11e9-8a2a-17321be3f184.png)

In my functions, they also failed with code
Action<Any, Any>.Action or Action.Action
![image](https://user-images.githubusercontent.com/17446246/53302620-17174c80-389b-11e9-8104-ae9277f1be62.png)

Zendesk is install from podfile, the same with Action
and if I import Zendesk without Action.
It works well.
Maybe I should break up my code in more little pieces.
Thanks a lot!

**Comment by bobgodwinx** [comment]
Try this it should work. 

```
swift

typealias FakeAction = Action

class FakeCalss {
    private let a: FakeAction<[Int], Int>
    private let b: FakeAction<[Int], String> { Observable.just("Fake-news") }

    init() {
         a = FakeAction { Observable.just($0.reduce(0, +)) }
    }

    func pushToProfessionOrgAction() -> FakeAction<String, Void> {
        return FakeAction { string in
            Observable.just(())
        }
    }
}
```

**Comment by fojas10** [comment]
Hi, also encountering the same issue. Difference is that zendesk is being imported from an Objective-C bridging header, otherwise, creating a new file with only import and typealias would have worked. Do you have any idea on how I can workaround this issue? Thanks
