### ISSUE TITLE
Xcode 10.1 Compatibility 

### ISSUE THREAD

**Issue by bobgodwinx** [RxSwiftCommunity/Action#179]
## Currently

The project workspace is at the moment not fully compatible with the latest `Version 10.1 (10B61)` of Xcode. 

## Required 

- [ ] Update the project and xcworkspace and make it compatible with `Version 10.1 (10B61)`
- [ ] Update the Unit test target and make it compatible with `Version 10.1 (10B61)`

**Comment by freak4pc** [comment]
We should push a new release out before closing this

**Comment by bobgodwinx** [comment]
I think Xcode version ‘10.1.0’ is not on circle. We should use ‘10.0.0’ for now I will change that so it will be all green 🥬

**Comment by freak4pc** [comment]
I’m a bit confused, 10.1.0 was all green yesterday
