### ISSUE TITLE
Action for UISwitch?

### ISSUE THREAD

**Issue by DhbStudy** [RxSwiftCommunity/Action#183]
I have one UISwitch in one UITableViewCell, and I'd like to have one action property for the UISwitch like UIButton.

Now, the extension of NSObject in "Action+Internal.swift" is internal. Can it be public? I must copy one in my project now and set it to public, is that suitable？

**Comment by bobgodwinx** [comment]
You can create an Action property, initialize it and bind the UISwitch.rx.value...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
