### ISSUE TITLE
Problem with execute  Driver<>

### ISSUE THREAD

**Issue by GlebGamaunov** [RxSwiftCommunity/Action#184]
HI all. I can't understood, how to bind action to some Driver.
I have 
```
struct Input {
    let editPet: Driver<RMPet>
}
```

and 
```
struct Output {
    let selectedPetAction: Action<RMPet, Void>
}
```

when user select model I set it to "editPet" Driver, but I can't execute "selectedPetAction"(i need go to edit screen)
Thanks!

**Comment by bobgodwinx** [comment]
I think you’re missing the parameters here.
 $0 = desired input 
```
Action.input
```
$1 = desired output
```
Action.elements
```
So in your case you can’t bind 
```
RMPet 
```
Into a 
```
Void
```


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GlebGamaunov** [comment]
Yea, I can't driver. An another way i do:
```
    // MARK: - Inputs
    lazy var selectedPet = petSelectedAction.inputs
```
```
    // MARK: - Actions
    private lazy var petSelectedAction = Action<RMPet, Void> { [unowned self] pet in
      return self.coordinator.rx.trigger(.petInfo(pet))
   }

```
and in VC:
```
         pet.bind(to: self.viewModel.input.selectedPet)
            .disposed(by: self.rx.disposeBag)
```

Thank you. I'm new so need a more read documentation :-)
