### ISSUE TITLE
Action Executed just Once

### ISSUE THREAD

**Issue by Dfmarulanda** [RxSwiftCommunity/Action#185]
I have an observable that's emited every time i tap a button; but it's action is just emited the first time.

```swift
    loginButton.rx.tap.withLatestFrom(loginInputs).do(onNext:{ _ in
      print("priting ever click")
    }).bind(to: viewModel.input.loginTrigger).disposed(by: disposeBag)

  // MARK: - Inputs
  private(set) lazy var loginTrigger: InputSubject<LoginInputs> = loginAction.inputs

  
  // MARK: - Actions
  
  private lazy var loginAction = Action<LoginInputs, ()> { [unowned self] inputs in
    print("doing just one")
    return Observable.combineLatest(self.userManager.login(email: inputs.email, password: inputs.password).asObservable(),self.userManager.currentUser.asObservable()).flatMap{ loggedIn, currentUser -> Observable<()> in
      if !loggedIn { return Observable.just(()) } //Login Failed
      if currentUser == nil { return self.router.rx.trigger(.activation)} // User Activated -> Need to set an activation code
      else { return self.router.rx.trigger(.home) } //Login + Activated
    }
  }
```

**Comment by bobgodwinx** [comment]
Please kindly take a look into the 
```
combineLatest
``` 
So nothing will ever be triggered more than once if value of usernames or passwords doesn’t change. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dfmarulanda** [comment]
I'm changing what's ion the inputs, so that's not the problem

**Comment by g-enius** [comment]
Same here. After the first trigger,  enabled is false

**Comment by g-enius** [comment]
I am doing like this, which only execute once.

Observable.of(self.watchNowButton.rx.tap, self.playButton.rx.tap)
            .merge()
            .withLatestFrom(mediaIDRelay)
            .bind(to:self.viewModel.playBackAction.inputs)
            .disposed(by: bag)

**Comment by g-enius** [comment]
Sorry guys, I figured out myself. In my action closure, I didn't complete the observable. So Action assumes I am executing forever. I resolved this issue by adding a ".take(1)" after an Observable sequence.
