### ISSUE TITLE
Action variants with multiple input parameters

### ISSUE THREAD

**Issue by fenuks** [RxSwiftCommunity/Action#186]
Hello,
when `execute` function has more than one input parameter, one has to resort to use tuple to encapsulate them. It works, but isn't perhaps the most convenient. Swift generics aren't flexible enough to support arbitrary number of generic input, but perhaps it would be worth to define Action with support to, say, up to five parameters, which should cover vast majority of use cases.

I don't know if I explained well enough what I mean. It would be handy to be allowed to write it like this (it's very silly example of course):

```swift
let action = Action<String, Int, String> { input, number in
    return .just(String(repeating: input, count: number)
}
```

**Comment by ashfurrow** [comment]
Hey, that's a totally valid use case. But as you point out, tuples solve this (or classes, whatever data type makes sense). I'd strongly prefer to keep the behaviour as-is, because it would introduce a lot of complexity to our library. The distinction between the following lines of code isn't a high priority for me, personally:

```diff
- let action = Action<(String, Int, String)> { input, number in
+ let action = Action<String, Int, String> { input, number in
```

Others are welcome to chime in too.

**Comment by fenuks** [comment]
I understand that for sake of simplicity it's preferable to stick with current design.

Version with tuple is a bit different.
```swift
 let action = Action<(String, Int), String> { input, number in
```

Although, at times swift is unable to infer types, and in such scenario it's required to use tuple in function parameter.

**Comment by bobgodwinx** [comment]
I agree with @ashfurrow. This would lead to complexities. @fenuks  the `input` is already a `Generic` parameter so you can inject whatever you want. In my case I mostly use `tuples` to work around multiple parameters enclosed in a `typealias` and the will shut swift compiler most of the time for me. Type putting your `tuples` into a `typealias`

**Comment by ashfurrow** [comment]
Yeah, `typealias` is a great idea! I wrote about that here: http://artsy.github.io/blog/2016/06/24/typealias-for-great-good/

**Comment by fenuks** [comment]
Thank you for suggestion (and link to an article!). It's a way to alleviate the problem, and improve readability. I will try that.
