### ISSUE TITLE
Runtime error in Demo project

### ISSUE THREAD

**Issue by azarovalex** [RxSwiftCommunity/Action#187]
I have troubles running the Demo target.

Steps to reproduce:
1) Run ./bin/bootstrap
2) Open .xcworkspace
3) Build the Demo target
4) See a runtime error

![image](https://user-images.githubusercontent.com/1976216/54517431-bb5c5280-4972-11e9-8a21-5884a8c13014.png)

**Comment by Aromxyz** [comment]
I have this issue too, this is my solution:
find the `Action.xcworkspace` and open it, then build the target with simulators, and find the `Action.framework` in Action, copy that and replace to your project's `Action.framework`, build your project target, It's OK, and if you want to build on your Device, the same way you should try, and if you want to build your target both with Simulators and Device, you can try to merge that two `Action. framework` and replace the framework in your target.
