### ISSUE TITLE
Is Action exection cancelable?

### ISSUE THREAD

**Issue by paulxi** [RxSwiftCommunity/Action#190]
Hi
I defined an Action instance to execute network request, and I also want to add a 'Cancel' button to the UI, so user can click 'Cancel' button to cancel the network request if it takes too long time. 

Could you please let me know how I can achieve this functionality with Action library?

Best Regards
Paul

**Comment by stefanomondino** [comment]
When you return the observable encapsulating the network request, you should add a .takeUntil(cancelButton.rx.tap) at the end (or something like that)

**Comment by paulxi** [comment]
@stefanomondino , thank you very much!
