### ISSUE TITLE
Carthage static library build failed

### ISSUE THREAD

**Issue by mauricekraus** [RxSwiftCommunity/Action#202]
**Carthage version 0.33.0**

**Cartfile:**

github "RxSwiftCommunity/Action" "4.0.1"
github "ReactiveX/RxSwift" 5.0.1

**Xcode Version 10.2.1**

Build is failing with this error:
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace .../Carthage/Checkouts/Action/Action.xcworkspace -scheme Action -configuration Release -derivedDataPath .../Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/Action/4.0.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/nf/9gnm1_9d5w54tcs77fg4k4nw0000gn/T/Action SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in .../Carthage/Checkouts/Action)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/nf/9gnm1_9d5w54tcs77fg4k4nw0000gn/T/carthage-xcodebuild.Sma9HW.log

Build is failing when  I try to build the project as a static library

``
carthage update --platform iOS --no-build
``
``
sh ./carthage-build-static.sh --platform ios
``

```
// carthage-build-static.sh
#!/bin/sh -e

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

echo "MACH_O_TYPE = staticlib" >> $xcconfig
echo "DEBUG_INFORMATION_FORMAT = dwarf" >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"

carthage build --platform ios --no-use-binaries
```

**Comment by bobgodwinx** [comment]
@mauricekraus `github "ReactiveX/RxSwift" 5.0.1` is for dynamic library builds. This library does not support `Static` builds at the moment. Please stick with `Dynamic` builds. You can find more info [here](https://github.com/ReactiveX/RxSwift/pull/1940) You can do some attempt with `RxSwift 5.0.0` but it's not advised.

**Comment by mauricekraus** [comment]
Please Check the readme of RxSwift they do support static builds, nevertheless building RxSwift standalone as static library works perfectly fine
