### ISSUE TITLE
Error when building with Carthage with XCode 11.0 beta 2

### ISSUE THREAD

**Issue by damianpop** [RxSwiftCommunity/Action#203]
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/dtroncoso/Desktop/DAMIAN-DEV/gymtracker/Carthage/Checkouts/Action/Action.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 6:
2019-06-21 16:36:01.201 xcodebuild[26576:2089589] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14855.21/IDEFoundation/ProjectModel/Containers/IDEContainer.m:553
Details:  Error: Mismatch between existing container extension: <DVTExtension 0x7fa9320083a0: Folder (Xcode.IDEFoundation.Container.Folder) v0.1 from com.apple.dt.IDEFoundation> and requested container extension: <DVTExtension 0x7fa9324285f0: Swift User Managed Package Folder (Xcode.IDEFoundation.Container.SwiftPackageUserManagedFolder) v0.1 from com.apple.dt.IDE.IDESwiftPackageSupport> for file path: <DVTFilePath:0x7fa932056660:'/Users/dtroncoso/Desktop/DAMIAN-DEV/gymtracker/Carthage/Checkouts/Action/Carthage/Build/iOS'>
Object:   <IDEContainer>
Method:   +_retainedContainerAtFilePath:fileDataType:workspace:options:error:
Thread:   <NSThread: 0x7fa92fc158d0>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
  4   _dispatch_client_callout (in libdispatch.dylib)
  5   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
  6   DVTDispatchBarrierSync (in DVTFoundation)
  7   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
  8   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
  9   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 10   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 11   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 12   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 13   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 14   -[IDEFileReference _recalculateReferencedContainer] (in IDEFoundation)
 15   -[IDEFileReference referencedContainer] (in IDEFoundation)
 16   -[IDEContainer _resolveFileReference:] (in IDEFoundation)
 17   __67-[IDEContainer initWithFilePath:extension:workspace:options:error:]_block_invoke.414 (in IDEFoundation)
 18   -[_DVTTimeSlicedMainThreadUnorderedUniquingWorkQueue _processWorkItemsWithDeadline:] (in DVTFoundation)
 19   -[DVTTimeSlicedMainThreadWorkQueue _processWithDeadline:] (in DVTFoundation)
 20   -[_DVTTimeSlicedMainThreadActiveWorkQueues _processWorkQueuesOnDeadline] (in DVTFoundation)
 21   __NSFireDelayedPerform (in Foundation)
 22   __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ (in CoreFoundation)
 23   __CFRunLoopDoTimer (in CoreFoundation)
 24   __CFRunLoopDoTimers (in CoreFoundation)
 25   __CFRunLoopRun (in CoreFoundation)
 26   CFRunLoopRunSpecific (in CoreFoundation)
 27   +[DVTKVOConditionValidator waitForCondition:sourceObject:keyPathAffectingConditionBlock:timeout:] (in DVTFoundation)
 28   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
 29   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 30   main (in xcodebuild)
 31   start (in libdyld.dylib)

**Comment by bobgodwinx** [comment]
Which version of MacOS are you using?

**Comment by damianpop** [comment]
10.14.5

**Comment by bobgodwinx** [comment]
I think you need Catalina to make it work properly because I am also having the same error when on Mojave and using Xcode 11 beta2. So try it with Catalina

**Comment by emildzwonek** [comment]
I have the same issue on Xcode 11.0 beta 3, both 10.14.5 and Catalina beta 3
