### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by tomburns** [RxSwiftCommunity/Action#21]
It'd be great if this repo included an Xcode project file, both to facilitate use with carthage and simply to build the micro framework without Cocoapods. I'll see if I can take a stab at it sometime soon.

**Comment by tomburns** [comment]
Spoke briefly with @kzaher about this on Slack, and it sounds like there are a couple other community projects currently undergoing a transition to supporting multiple package managers. I'd be happy to do the grunt work once we settle on a good pattern for doing this. :fries:

**Comment by ashfurrow** [comment]
Fabbo, thanks! Looking forward to seeing how the dust settles on all this :)

**Comment by zdenektopic** [comment]
still no update?

**Comment by ashfurrow** [comment]
Not that I'm aware of. If you have any suggestions, let us know or send a PR :smile:

**Comment by zdenektopic** [comment]
Carthage just needs xcodeproj with shared scheme and Cartfile with dependency to RxSwift.

**Comment by ashfurrow** [comment]
Super! I don't use Carthage, could you send a pull request?

**Comment by zdenektopic** [comment]
I'll try later today or tomorrow :)

**Comment by ReedD** [comment]
:+1:

**Comment by edopelawi** [comment]
Guys, is it possible to add the Carthage-related commit to a new tag? It feels awkward to directly specify `master` branch or the commit tag on the Cartfile 😐 

Thanks in advance!

**Comment by ashfurrow** [comment]
Ah, I see. Just a tag on master will do?

**Comment by edopelawi** [comment]
Totally! Something like `1.2.1-carthage` will do :)

**Comment by ashfurrow** [comment]
Done! Let me know if there's anything else we can do to make it easier to use. I don't use Carthage so sometimes things get overlooked, appreciate you all helping make the library more usable by all :bow:

**Comment by edopelawi** [comment]
Sweet! Thanks a bunch guys! 😄

**Comment by piotr-dudek** [comment]
Hi guys.
Thanks for Carthage support.

@ashfurrow one thing: `1.2.1-carthage` release also contains an important fix: [fixed observable's disposing](https://github.com/RxSwiftCommunity/Action/pull/33). Since `1.2.1-carthage` is not available through cocoapods, could you release version `1.2.2`, please?

**Comment by ashfurrow** [comment]
Ah, oops. On it.

**Comment by ashfurrow** [comment]
Should be good now 👍

**Comment by piotr-dudek** [comment]
@ashfurrow thanks for quick response. For some reason cocoapods can not install `1.2.2` version. When I will not specify the version it is installing `1.2.1`, and when I do specify `1.2.2` I get `None of your spec sources contain a spec satisfying the dependency: Action (= 1.2.2)`

**Comment by ashfurrow** [comment]
@piotr-dudek can you run `pod repo update`? It will update your machine to the latest CocoaPods specs. CocoaPods used to do this automatically, but changed due to performance issues on the Specs repo. There's [more info here](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/).

**Comment by werediver** [comment]
@ashfurrow (or anyone privileged enough) this issue seems to be *fixed* since v1.2.1.

Let's close the ticket.

**Comment by ashfurrow** [comment]
Sure thing, thanks for the update.
