### ISSUE TITLE
Crash when using Carthage-cache and Rx v5.1.1

### ISSUE THREAD

**Issue by vishreddy** [RxSwiftCommunity/Action#217]
Let me start by saying that this library is awesome! We extensively use it for confluence at Atlassian. 

**Problem:**
We are trying to upgrade Rx to v5.1.1. We also use Carthage-cache to upload all the dependencies to an s3 bucket so it's extremely fast for us to download dependencies rather then build them every time we update any dependencies. The combination of this two is causing a crash to us. We believe it's because of change of ABI in RxSwift 5.1.1 which cased a prebuild binary Action to crash. 
The reason being Carthage-cache only gets updated by our CI when a version of a library changes and since this library is the same since RxSwift 5.1.1 was released, it stays the same. But Rx gets updated and then because of incompatible API we crash. So anyone leveraging similar level of build automation will see this problem.

**Solution**
I see two ways to fix this issue:

1. Confluence can delete the cache for this version locally and rebuild the library.
2. We bump the version number of this library here and that triggers a new build with latest Xcode when our build system run Carthage update.

We are doing something close to option 1 for now. But all the other people using Carthage-cache and this awesome library will run into the same problem when upgrading to latest RxSwift. 

I'm proposing that we bump this library a minor version(4.0.2) as a solution. I can upload the stack trace for the crash if y'all need. Let me know if what I proposed makes sense at all. IF not I can explain it better.

**Comment by nikita-leonov** [comment]
Just to add some color, the issue we have is due to [Module stability](https://swift.org/blog/abi-stability-and-more/), not an ABI stability per se even thought they are related. Module stability is guaranteed in Swift 5.1 and was released on [September 20, 2019](https://swift.org/blog/swift-5-1-released/). Last release of Action was May 6, 2019, so binary are not resilient to change of swift  versions. Re-building and re-releasing with Xcode 11.3.1 and proper RxSwift in place will solve the problem. 🥂

**Comment by vishreddy** [comment]
Since the release here does not involve building the framework, I think a new release is not needed and we can clear Carthage cache on our and build the frameworks. Sorry for the noise! I'll go ahead and close the ticket. 🙏🏽

**Comment by ashfurrow** [comment]
No worries at all – happy to have your onboard!
