### ISSUE TITLE
Pod version not updated

### ISSUE THREAD

**Issue by marcelodeaguiar** [RxSwiftCommunity/Action#218]
The pod version still points to version 4.0.0 instead of the lastest release 4.0.1

**Comment by ashfurrow** [comment]
4.0.1 fixed a problem with Carthage integration and is otherwise identical to 4.0.0. We _do_ have some unreleased code on master though, and should probably release 👍

**Comment by ashfurrow** [comment]
I've released the work on master as 4.1.0 and the versions between CocoaPods and Carthage should now match 👍
