### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/Action#219]
Carthage is erroring out on the dreaded "exit code 65" ([example build](https://circleci.com/gh/RxSwiftCommunity/Action/161)). It works locally, though. I don't know enough about Carthage to fix it, maybe someone else can take a look?

**Comment by Econa77** [comment]
@ashfurrow I got the same error when I built it using Xcode10.3 in locally.
The error appears to be in the `return` omission on this line.
https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/iOS/Proxies/RxWKNavigationDelegateProxy.swift#L35

It can be solved by upgrading the version of Xcode in the CI environment.

**Comment by ashfurrow** [comment]
Ahhhh good catch! I'll take that as a follow up.
