### ISSUE TITLE
Building for iOS, but the linked framework 'RxCocoa.framework' was built for macOS. (in target 'Action' from project 'Action')

### ISSUE THREAD

**Issue by 0xhiroki** [RxSwiftCommunity/Action#221]
I'm using Xcode 11.4. Every time I run:
```
carthage update --platform iOS
```
It gives me the following error (on console):

```
Building for iOS, but the linked framework 'RxCocoa.framework' was built for macOS. (in target 'Action' from project 'Action')
```

I deleted derived data and Cartfile.resolved, and tried again but no luck so far.

**Comment by bobgodwinx** [comment]
Hi @0xhiroki Sorry for the late reply but I couldn't reproduce this error. I built successfully with: `swiftlang-1103.0.32.6 clang-1103.0.32.51`

**Comment by alvarozizou** [comment]
Same problem right here with Xcode 11.5

I've tried it with --platform iOS and without --platform iOS, but I get the same error.

I have `swiftlang-1103.0.32.9 clang-1103.0.32.53`

**Comment by Econa77** [comment]
@0xhiroki @bobgodwinx @alvarozizou  I was able to reproduce this problem. Can you try to see if you can build with this setup?
```Cartfile
github "Econa77/Action" "feature/fix-carthage-build"
```

**Comment by alvarozizou** [comment]
@Econa77 it works!!!

**Comment by bobgodwinx** [comment]
Sounds like a plan.. I'll merge and create a minor version later.. @Econa77 thanks for figuring out the xcode mystery.
