### ISSUE TITLE
Action not executed anymore

### ISSUE THREAD

**Issue by anas10** [RxSwiftCommunity/Action#76]
Hi,

I went back on a project on which I didn't work recently. Then I realised that my Actions were not executed anymore. I updated to Action 2.2.1 after seeing that some fix were added after other issues but it's still not working.

Here is the function I am trying to execute : 
```
func presentSetNewPasswordViewController(_ presentingViewController: UIViewController) -> CocoaAction {
        return CocoaAction { _ in
            return Observable.create { observer -> Disposable in

                let navVC = self.instantiateEmbedSetNewPasswordViewController()
                navVC.modalPresentationStyle = UIModalPresentationStyle.formSheet
                presentingViewController.present(navVC, animated: true) {
                    observer.onCompleted()
                }
                return Disposables.create()
            }
        }
    }
```

And I execute it like this: 
```
authenticationWireframe.presentSetNewPasswordViewController(window.rootViewController!).execute()
```

Am I doing something wrong here? Because this is definitely working on the prod app.

Thanks.

**Comment by fpillet** [comment]
You need to somehow keep a reference to the action. Since 2.0, it doesn't auto-references when you subscribe to `elements` or bind to `inputs`. Would it be what you're doing?

**Comment by anas10** [comment]
In this case, I just want to execute the action manually. I was wondering if it was a referencing issue but still didn't manage to solve it. Would you have a similar example by any chance?

**Comment by fpillet** [comment]
yeah I believe the problem is that you need to keep the action object around until execution is complete. I'm not sure about the precise timing here, but try keeping the Action object in a property somewhere (for testing), and your presentation should work

**Comment by anas10** [comment]
Yes, it works for me now. It was easier before though but I guess there is a reason for that change :)
