### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/Action#83]
First failure here: https://travis-ci.org/RxSwiftCommunity/Action/builds/220553535

> /Users/travis/build/RxSwiftCommunity/Action/Sources/Action/Action.swift:99:14: error: value of type 'Observable<Bool>' has no member 'bindTo'

Looks like RxSwift might not be adhering to semver? Help would be welcome here :bow:

**Comment by freak4pc** [comment]
Seems like this is good to by closed? Not seeing any errors in CI ATM
