### ISSUE TITLE
requires RxBlocking @ runtime!

### ISSUE THREAD

**Issue by bidadh** [RxSwiftCommunity/Action#84]
I cannpt add Action to my project using Carthage

I'm getting 

> **dyld: Library not loaded: @rpath/RxBlocking.framework/RxBlocking**

>  **Referenced from: ...app/Frameworks/Action.framework/Action
  Reason: image not found**

at runtime and obviously RxBlocking is Test library

NOTE: adding RxBlocking fixed runtime issue but I cannot push the binary to itunesconnect

**Comment by ashfurrow** [comment]
Very strange, can anyone from @RxSwiftCommunity/contributors take a look at this? I'm unfamiliar with how Carthage is integrated with the Action library.

**Comment by reloni** [comment]
@ashfurrow you already merged pull request #79 that fixes this problem, but latest git tag (2.2.1) was made before that merge, so new release (like 2.2.2) will fix that problem.

**Comment by bidadh** [comment]
@reloni Thanks for the update.
@ashfurrow When do you release next version?

**Comment by ashfurrow** [comment]
Working on it right now.

**Comment by ashfurrow** [comment]
Should be good to go, version 2.2.2 pushed. Let me know.

**Comment by bidadh** [comment]
It works fine with 2.2.2
Thanks @ashfurrow

**Comment by bidadh** [comment]
@ashfurrow It's been resolved in 2.2.2 so that I can run locally but I'm unable to push to iTunesConnect!
the app including Action.framework gets 'This build is invalid' error after Processing and if I remove Action then it succeeds.

Any thoughts?

**Comment by stefanomondino** [comment]
Did you add the Action framework in Carthage's custom build phase script?

**Comment by bidadh** [comment]
@stefanomondino Yes I do

**Comment by bidadh** [comment]
The only thing I guess could be the reason is I looked inside the built Action.framework and the version in Info.plist is 2.1.1! compare to when I use pod which is 2.2.2

my cartfile.resolved includes `github "RxSwiftCommunity/Action" "2.2.2"`

**Comment by bidadh** [comment]
2.3 fixes this issue.
Thanks
