### ISSUE TITLE
Podspec not updated for 2.3.0

### ISSUE THREAD

**Issue by tomburns** [RxSwiftCommunity/Action#85]
Can we please get the podspec pushed to the main specs repo? Looks like this got lost in the update shuffle again.

**Comment by tomburns** [comment]
cc @ashfurrow who I think holds the keys still

**Comment by ashfurrow** [comment]
Sure sure, I'll do my best to get that in this afternoon.

**Comment by ashfurrow** [comment]
Okay, should be good. Let me know 👍

**Comment by tomburns** [comment]
`Installing Action 2.3.0 (was 2.2.1)`

you're the best, thanks Ash 😘
