### ISSUE TITLE
Deprecation warnings when using Rx >= 3.4.0

### ISSUE THREAD

**Issue by tomburns** [RxSwiftCommunity/Action#86]
This is probably a quick fix, but I'm not certain how we'd want to version it, nor am I terribly familiar with Carthage. tl;dr `bindTo()` -> `bind(to:)`

**Comment by ashfurrow** [comment]
Yeah yeah, I'd love a PR if you have time but no worries!

**Comment by tomburns** [comment]
If someone wants to point me in the right direction, I can probably take care of this and open a PR.

**Comment by ashfurrow** [comment]
This would be a major version change, but just it in the changelog and it'll be fine 👍 Update the source code to use the new method, and require the cartfile/podspec to require `~> 3.4`.

**Comment by tomburns** [comment]
Sounds good, I'm on it! thanks again :)
