### ISSUE TITLE
3.0.0 Release

### ISSUE THREAD

**Issue by tomburns** [RxSwiftCommunity/Action#88]
I should have some time this weekend to finalize a release of the changes that were merged yesterday; is there anything else we want to get in before that goes out? If so, I can try to tackle it, otherwise I'm going to touch up the Readme and give the docs a once-over and open a PR with that to get started.

**Comment by ashfurrow** [comment]
Somes great, thanks!

**Comment by tomburns** [comment]
This is still on my to-do list, but I obviously didn't have the time I expected to over the weekend. If anyone else wants to grab it to get the release out feel free, otherwise I'll get back to it ASAP

**Comment by freak4pc** [comment]
Closing by #87
