### ISSUE TITLE
[Feature Request] Replace PublishSubject

### ISSUE THREAD

**Issue by Econa77** [RxSwiftCommunity/Action#91]
If error or completed flows in PublishSubject of inputs, further action can not be fired.
https://github.com/RxSwiftCommunity/Action/blob/master/Sources/Action/Action.swift#L30

How do you think inputs should receive onNext only?
I think ReactorKit's ActionSubject is a good example.
https://github.com/ReactorKit/ReactorKit/blob/master/Sources/ActionSubject.swift

If you accept the feature request I will create a PR.

**Comment by ashfurrow** [comment]
Interesting, thanks for opening the issue. I only ever thought inputs would receive onNext, but it's certainly possible. @ishkawa what do you think?

**Comment by ishkawa** [comment]
+1 for this.

Action.inputs does not expect onError and onCompleted, and it turns unrecoverable state when these kind of events occur. Currently, developers should be careful to avoid onError and onCompleted in inputs. If inputs subject get onNext only, developers don't have to care about that.

**Comment by ashfurrow** [comment]
Awesome, let's do it. @Econa77 would you be available to open a pull request?

**Comment by Econa77** [comment]
OK 👍 I will create PullRequest.

**Comment by Econa77** [comment]
Submitted a PullRequest #92 😄

**Comment by dangthaison91** [comment]
+1. I had to use `ignoreErrorAndCompleted = ignoreErrors.concat(Observale.never())` in previous project.

**Comment by sunshinejr** [comment]
Closing this thread in favor of #92.
